# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Sun Nov 24 17:12:51 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 566)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 761, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 741, 417))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 14, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 6, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 13, 0, 1, 1)
        self.lineEdit_IPProt = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPProt.setObjectName("lineEdit_IPProt")
        self.gridLayout_3.addWidget(self.lineEdit_IPProt, 8, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 9, 0, 1, 1)
        self.lineEdit_IPOpt = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPOpt.setObjectName("lineEdit_IPOpt")
        self.gridLayout_3.addWidget(self.lineEdit_IPOpt, 12, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 0, 1, 1)
        self.lineEdit_IPLen = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPLen.setObjectName("lineEdit_IPLen")
        self.gridLayout_3.addWidget(self.lineEdit_IPLen, 3, 1, 1, 1)
        self.lineEdit_IPIHL = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPIHL.setObjectName("lineEdit_IPIHL")
        self.gridLayout_3.addWidget(self.lineEdit_IPIHL, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 12, 0, 1, 1)
        self.plainTextEdit_IPData = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_3)
        self.plainTextEdit_IPData.setObjectName("plainTextEdit_IPData")
        self.gridLayout_3.addWidget(self.plainTextEdit_IPData, 13, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 4, 0, 1, 1)
        self.lineEdit_IPFrag = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPFrag.setObjectName("lineEdit_IPFrag")
        self.gridLayout_3.addWidget(self.lineEdit_IPFrag, 6, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 8, 0, 1, 1)
        self.lineEdit_IPTTL = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPTTL.setObjectName("lineEdit_IPTTL")
        self.gridLayout_3.addWidget(self.lineEdit_IPTTL, 7, 1, 1, 1)
        self.lineEdit_IPTOS = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPTOS.setObjectName("lineEdit_IPTOS")
        self.gridLayout_3.addWidget(self.lineEdit_IPTOS, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 11, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 5, 0, 1, 1)
        self.lineEdit_IPChecksum = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPChecksum.setObjectName("lineEdit_IPChecksum")
        self.gridLayout_3.addWidget(self.lineEdit_IPChecksum, 9, 1, 1, 1)
        self.lineEdit_IPID = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPID.setObjectName("lineEdit_IPID")
        self.gridLayout_3.addWidget(self.lineEdit_IPID, 4, 1, 1, 1)
        self.lineEdit_IPFlags = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPFlags.setObjectName("lineEdit_IPFlags")
        self.gridLayout_3.addWidget(self.lineEdit_IPFlags, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 7, 0, 1, 1)
        self.lineEdit_IPVersion = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPVersion.setObjectName("lineEdit_IPVersion")
        self.gridLayout_3.addWidget(self.lineEdit_IPVersion, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 10, 0, 1, 1)
        self.lineEdit_IPSrc = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPSrc.setObjectName("lineEdit_IPSrc")
        self.gridLayout_3.addWidget(self.lineEdit_IPSrc, 10, 1, 1, 1)
        self.lineEdit_IPDst = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_IPDst.setObjectName("lineEdit_IPDst")
        self.gridLayout_3.addWidget(self.lineEdit_IPDst, 11, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 741, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)
        self.lineEdit_UDPLen = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_UDPLen.setObjectName("lineEdit_UDPLen")
        self.gridLayout.addWidget(self.lineEdit_UDPLen, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_UDPDst = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_UDPDst.setObjectName("lineEdit_UDPDst")
        self.gridLayout.addWidget(self.lineEdit_UDPDst, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_UDPChecksum = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_UDPChecksum.setObjectName("lineEdit_UDPChecksum")
        self.gridLayout.addWidget(self.lineEdit_UDPChecksum, 3, 1, 1, 1)
        self.lineEdit_UDPSrc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_UDPSrc.setObjectName("lineEdit_UDPSrc")
        self.gridLayout.addWidget(self.lineEdit_UDPSrc, 0, 1, 1, 1)
        self.plainTextEdit_UDPData = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit_UDPData.setObjectName("plainTextEdit_UDPData")
        self.gridLayout.addWidget(self.plainTextEdit_UDPData, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 741, 365))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 7, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 10, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 9, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 8, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 12, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 11, 0, 1, 1)
        self.lineEdit_TCPOptions = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPOptions.setObjectName("lineEdit_TCPOptions")
        self.gridLayout_2.addWidget(self.lineEdit_TCPOptions, 10, 1, 1, 1)
        self.lineEdit_TCPOptionValue = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPOptionValue.setObjectName("lineEdit_TCPOptionValue")
        self.gridLayout_2.addWidget(self.lineEdit_TCPOptionValue, 10, 2, 1, 1)
        self.lineEdit_TCPSrc = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPSrc.setObjectName("lineEdit_TCPSrc")
        self.gridLayout_2.addWidget(self.lineEdit_TCPSrc, 0, 1, 1, 2)
        self.lineEdit_TCPDst = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPDst.setObjectName("lineEdit_TCPDst")
        self.gridLayout_2.addWidget(self.lineEdit_TCPDst, 1, 1, 1, 2)
        self.lineEdit_TCPSeq = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPSeq.setObjectName("lineEdit_TCPSeq")
        self.gridLayout_2.addWidget(self.lineEdit_TCPSeq, 2, 1, 1, 2)
        self.lineEdit_TCPAck = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPAck.setObjectName("lineEdit_TCPAck")
        self.gridLayout_2.addWidget(self.lineEdit_TCPAck, 3, 1, 1, 2)
        self.lineEdit_TCPDataOffset = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPDataOffset.setObjectName("lineEdit_TCPDataOffset")
        self.gridLayout_2.addWidget(self.lineEdit_TCPDataOffset, 4, 1, 1, 2)
        self.lineEdit_TCPReserved = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPReserved.setObjectName("lineEdit_TCPReserved")
        self.gridLayout_2.addWidget(self.lineEdit_TCPReserved, 5, 1, 1, 2)
        self.lineEdit_TCPFlags = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPFlags.setObjectName("lineEdit_TCPFlags")
        self.gridLayout_2.addWidget(self.lineEdit_TCPFlags, 6, 1, 1, 2)
        self.lineEdit_TCPWindow = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPWindow.setObjectName("lineEdit_TCPWindow")
        self.gridLayout_2.addWidget(self.lineEdit_TCPWindow, 7, 1, 1, 2)
        self.lineEdit_TCPChecksum = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPChecksum.setObjectName("lineEdit_TCPChecksum")
        self.gridLayout_2.addWidget(self.lineEdit_TCPChecksum, 8, 1, 1, 2)
        self.lineEdit_TCPUrgent = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_TCPUrgent.setObjectName("lineEdit_TCPUrgent")
        self.gridLayout_2.addWidget(self.lineEdit_TCPUrgent, 9, 1, 1, 2)
        self.plainTextEdit_TCPData = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_2)
        self.plainTextEdit_TCPData.setObjectName("plainTextEdit_TCPData")
        self.gridLayout_2.addWidget(self.plainTextEdit_TCPData, 11, 1, 1, 2)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_7)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 741, 351))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 5, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 6, 1, 1, 1)
        self.lineEdit_ICMPChecksum = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_ICMPChecksum.setObjectName("lineEdit_ICMPChecksum")
        self.gridLayout_4.addWidget(self.lineEdit_ICMPChecksum, 2, 1, 1, 1)
        self.lineEdit_ICMPCode = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_ICMPCode.setObjectName("lineEdit_ICMPCode")
        self.gridLayout_4.addWidget(self.lineEdit_ICMPCode, 1, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 2, 0, 1, 1)
        self.lineEdit_ICMPID = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_ICMPID.setObjectName("lineEdit_ICMPID")
        self.gridLayout_4.addWidget(self.lineEdit_ICMPID, 3, 1, 1, 1)
        self.plainTextEdit_ICMPData = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.plainTextEdit_ICMPData.setObjectName("plainTextEdit_ICMPData")
        self.gridLayout_4.addWidget(self.plainTextEdit_ICMPData, 5, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 1, 0, 1, 1)
        self.lineEdit_ICMPType = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_ICMPType.setObjectName("lineEdit_ICMPType")
        self.gridLayout_4.addWidget(self.lineEdit_ICMPType, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 4, 0, 1, 1)
        self.lineEdit_ICMPSeq = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_ICMPSeq.setObjectName("lineEdit_ICMPSeq")
        self.gridLayout_4.addWidget(self.lineEdit_ICMPSeq, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_Queue = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_Queue.setGeometry(QtCore.QRect(10, 10, 741, 421))
        self.tableWidget_Queue.setObjectName("tableWidget_Queue")
        self.tableWidget_Queue.setColumnCount(6)
        self.tableWidget_Queue.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Queue.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Queue.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Queue.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Queue.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Queue.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Queue.setHorizontalHeaderItem(5, item)
        self.tabWidget.addTab(self.tab_8, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_create = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout.addWidget(self.pushButton_create)
        self.pushButton_send = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout.addWidget(self.pushButton_send)
        self.pushButton_choose_int = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_choose_int.setObjectName("pushButton_choose_int")
        self.horizontalLayout.addWidget(self.pushButton_choose_int)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.comboBox_interface = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_interface.setObjectName("comboBox_interface")
        self.verticalLayout.addWidget(self.comboBox_interface)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "Fragment offset", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "Type of Service(8 bits)", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("MainWindow", "Internet Header Length", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "Length", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "Data", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "Checksum", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("MainWindow", "Version", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "Identificator", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Protocol <----", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "Destination IP", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Flags(3 bits)", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "TTL", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "Source IP", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtWidgets.QApplication.translate("MainWindow", "IP", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Cheksum", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Source Port", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Data", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Length", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Destination Port", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtWidgets.QApplication.translate("MainWindow", "UDP", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "Window size", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "Sequence number", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Urgent pointer", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Checksum", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Data offset", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "Destination Port", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "Flags(9 bits)", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Acknowlegment number", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Source Port", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Reserved", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Data", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtWidgets.QApplication.translate("MainWindow", "TCP", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "Type", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "Data", None, -1))
        self.label_32.setText(QtWidgets.QApplication.translate("MainWindow", "Identificator", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "Checksum", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "Code", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "Sequence number", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QtWidgets.QApplication.translate("MainWindow", "ICMP", None, -1))
        self.tableWidget_Queue.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Protocol", None, -1))
        self.tableWidget_Queue.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "IP_Src", None, -1))
        self.tableWidget_Queue.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "IP_Dst", None, -1))
        self.tableWidget_Queue.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Port_Src", None, -1))
        self.tableWidget_Queue.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Port_Dst", None, -1))
        self.tableWidget_Queue.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "ICMP_Type", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QtWidgets.QApplication.translate("MainWindow", "Queue", None, -1))
        self.pushButton_create.setText(QtWidgets.QApplication.translate("MainWindow", "Create", None, -1))
        self.pushButton_send.setText(QtWidgets.QApplication.translate("MainWindow", "Send", None, -1))
        self.pushButton_choose_int.setText(QtWidgets.QApplication.translate("MainWindow", "Choose interface", None, -1))

